import type { AfendaGuidance } from "@/lib/afenda-guidance";

export const CUSTOM_FIELD_GUIDANCE: Record<
  "scope" | "dataType" | "key" | "label" | "placeholder" | "description" | "required" | "showInList" | "options",
  AfendaGuidance
> = {
  scope: {
    summary: "Choose which kind of Corporate Administration record will display this field.",
    what: "The record scope where the custom field belongs: counterparty, obligation, due item, or payment.",
    why: "Scoping prevents unrelated records from being cluttered with information that does not apply to them.",
    who: "An administrator who understands where the information is created and maintained.",
    when: "Choose it when defining the field; treat the scope as part of the field's identity.",
    how: "Select the narrowest record type that naturally owns the information.",
    example: "Insurance policy number → Obligation; bank settlement batch → Payment.",
  },
  dataType: {
    summary: "Choose the input type that matches the information users must enter.",
    what: "The validation and control type used for this custom field.",
    why: "Typed fields keep data more consistent than unrestricted text and allow Afenda to render the correct control automatically.",
    who: "The administrator defining the custom field.",
    when: "Choose it when the field is created. Avoid changing meaning later; create a new field when the information type genuinely changes.",
    how: "Use Text, Long text, Number, Date, Boolean, Select, URL, Email, or Phone according to the real business value.",
    example: "Renewal classification with fixed choices → Select.",
  },
  key: {
    summary: "A stable machine-readable identifier; users normally see the label, not this key.",
    what: "The internal key used to store the custom field value inside the record's governed custom-field data.",
    why: "Stable keys let labels improve later without breaking historical values or future integrations.",
    who: "The administrator defining the field.",
    when: "Set it once when the field is created and do not repurpose it for a different meaning.",
    how: "Use short lowercase words separated by underscores, with no spaces or punctuation.",
    example: "policy_number",
  },
  label: {
    summary: "The plain-language field name users will see on forms and records.",
    what: "The human-readable title of the custom field.",
    why: "A clear label reduces training and makes the field understandable without knowing its internal key.",
    who: "The administrator defining the field, ideally using terminology familiar to the people who will enter it.",
    when: "Set it at creation; it may be refined later without changing the stable key.",
    how: "Use a short noun phrase that describes the value, not an instruction sentence.",
    example: "Insurance policy number",
  },
  placeholder: {
    summary: "Optional example text shown inside an empty control before the user enters a value.",
    what: "A short formatting hint for the expected value.",
    why: "It can show the desired pattern without turning the label into a long instruction.",
    who: "The administrator defining the field.",
    when: "Use it when an example materially helps entry; leave it blank when the input is self-explanatory.",
    how: "Show a realistic format, not important guidance that would disappear once the user starts typing.",
    example: "POL-MY-2026-01882",
  },
  description: {
    summary: "Short on-screen help explaining what users should enter and how to recognise the correct value.",
    what: "The helper text displayed with the custom field.",
    why: "Custom fields should be self-explanatory so adding one does not create a new training or support ticket.",
    who: "The administrator defining the field.",
    when: "Provide it whenever the label alone could be interpreted in more than one way.",
    how: "Write one concise sentence: what the value means and where the user normally finds it.",
    example: "Policy number shown on the insurer's policy document.",
  },
  required: {
    summary: "Require a value whenever this active custom field is validated on its record.",
    what: "A validation rule marking the custom field as mandatory.",
    why: "Use it for information the process genuinely cannot proceed without, not merely information that is nice to have.",
    who: "The administrator or process owner defining the requirement.",
    when: "Turn it on only when missing the value would make the record incomplete or unusable.",
    how: "Ask whether users should be blocked when this value is unknown. If not, leave the field optional.",
    example: "Policy number may be required for an insurance obligation; secondary contact phone may remain optional.",
  },
  showInList: {
    summary: "Allow the field to appear as a configurable column in record lists where supported.",
    what: "A presentation hint for important custom fields that users need while scanning many records.",
    why: "Lists should surface only high-value comparison information instead of every custom field.",
    who: "The administrator defining the field.",
    when: "Enable it when users regularly need the value before opening a record.",
    how: "Prefer short values that compare well in a column; keep long notes and URLs off list views.",
    example: "Property code → show in list; detailed renewal notes → do not show in list.",
  },
  options: {
    summary: "For Select fields, define the controlled choices users are allowed to pick.",
    what: "The fixed list of values rendered in the Select control.",
    why: "Controlled choices prevent spelling variants and make filtering/reporting dependable.",
    who: "The administrator or process owner defining the accepted business vocabulary.",
    when: "Required when the field type is Select.",
    how: "Enter one clear option per line. Keep choices mutually understandable and avoid duplicate meanings.",
    example: "Monthly\nQuarterly\nAnnual",
  },
};
