import type { AfendaGuidance } from "@/lib/afenda-guidance";

function guidance(value: AfendaGuidance): AfendaGuidance {
  return value;
}

export const OBLIGATION_GUIDANCE = {
  code: guidance({
    summary: "A stable internal reference for this obligation; Afenda can generate one if you leave it blank.",
    what: "The internal code used to identify this obligation independently from a supplier invoice, contract number, or payment reference.",
    why: "A stable code makes searching, audit trails, exports, and later integrations reliable even when external references change.",
    who: "The administrator creating the obligation, unless your organisation has a prescribed coding convention.",
    when: "Set it when the obligation is created. Avoid changing it after the record is in active use.",
    how: "Use your organisation's normal naming convention, or leave it blank and let Afenda generate the code.",
    example: "ADM-2026-0042",
  }),
  organization: guidance({
    summary: "The legal entity or operating organisation responsible for this obligation.",
    what: "The organisation that owns the commitment and is expected to administer or settle it.",
    why: "Corporate Administration needs to distinguish obligations belonging to different group entities or operating units.",
    who: "The record owner or administrator who knows which entity entered into the arrangement.",
    when: "Enter it when creating the obligation and change it only if the underlying responsibility genuinely changes.",
    how: "Use the organisation's canonical short name or code consistently across records.",
    example: "DLBB",
  }),
  category: guidance({
    summary: "The operational type of obligation, used for filtering and reporting.",
    what: "A practical classification such as tenancy, insurance, licence, subscription, maintenance, fleet, utilities, or professional services.",
    why: "Categories let users find similar obligations quickly without creating separate modules for every administrative use case.",
    who: "The administrator entering the record.",
    when: "Choose it when the obligation is created and update it if the original classification was incorrect.",
    how: "Use the closest existing business category. Create a custom field for extra detail instead of inventing overly specific categories.",
    example: "Tenancy",
  }),
  title: guidance({
    summary: "A short human-readable name that lets users recognise the obligation immediately.",
    what: "The working title displayed in lists, attention queues, and record headers.",
    why: "Users should be able to understand the obligation without opening the contract or decoding its reference number.",
    who: "The administrator creating the record.",
    when: "Set it at creation and keep it stable unless the scope materially changes.",
    how: "Name the subject and location or purpose in plain business language.",
    example: "Office tenancy — Klang",
  }),
  counterparty: guidance({
    summary: "The external party you contract with, owe, or receive the administrative service from.",
    what: "The vendor, landlord, insurer, financier, service provider, authority, or other party connected to this obligation.",
    why: "Counterparty linkage keeps contact, payment terms, currency, and obligation history together.",
    who: "The administrator who knows the contracting or billing party.",
    when: "Select it when creating the obligation. Create the counterparty first if it does not exist.",
    how: "Choose the party named on the agreement or invoice, not an informal contact person.",
    example: "ABC Properties Sdn Bhd",
  }),
  owner: guidance({
    summary: "The internal person accountable for keeping this record current and following up actions.",
    what: "The workspace user responsible for the obligation's operational maintenance.",
    why: "Ownership makes follow-up clear without turning Corporate Administration into a workflow engine.",
    who: "Assign the person who is expected to monitor the agreement, renewal, invoice, or payment process.",
    when: "Assign at creation or when responsibility is handed over.",
    how: "Choose the accountable person, not everyone involved. Other participants can be recorded in notes or custom fields if needed.",
    example: "Corporate admin manager responsible for the tenancy portfolio",
  }),
  assetReference: guidance({
    summary: "The premise, vehicle, account, asset, policy, or location this obligation relates to.",
    what: "An operational reference that connects the obligation to the thing being administered.",
    why: "It helps users distinguish otherwise similar contracts or recurring charges without adding a full asset-management module.",
    who: "The administrator maintaining the obligation.",
    when: "Use it whenever a specific asset, location, account, or policy makes the record easier to identify.",
    how: "Enter the most useful internal or external reference in plain text.",
    example: "Shop Lot G-12 / Vehicle WXY1234 / Policy P123456",
  }),
  paymentMethod: guidance({
    summary: "The normal settlement method expected for this obligation.",
    what: "The usual way payments are made, such as bank transfer, direct debit, card, cheque, or other approved method.",
    why: "It gives the payment workflow useful context before the actual settlement is recorded.",
    who: "The administrator or finance user who knows the agreed payment method.",
    when: "Set it when the normal method is known. The actual payment record can still capture a different method if necessary.",
    how: "Use the standard method name used by your organisation.",
    example: "BANK_TRANSFER",
  }),
  startDate: guidance({
    summary: "The date the obligation or agreement begins.",
    what: "The commercial or administrative start date of the arrangement.",
    why: "It anchors the obligation period and supports date validation, renewal context, and historical reporting.",
    who: "The administrator using the source agreement or approved record.",
    when: "Enter it at creation from the agreement or confirmed commencement date.",
    how: "Use the date stated in the agreement. Do not substitute the date the record was entered into Afenda.",
    example: "01 Aug 2026",
  }),
  endDate: guidance({
    summary: "The contractual or expected end date, if the obligation has one.",
    what: "The date the arrangement expires or ceases under its current terms.",
    why: "It helps users identify expiries and distinguish fixed-term arrangements from open-ended ones.",
    who: "The administrator maintaining the agreement.",
    when: "Enter it when the agreement specifies an end date. Leave blank for genuinely open-ended arrangements.",
    how: "Use the contractual end date, not the next payment or renewal date.",
    example: "31 Jul 2027",
  }),
  expectedAmount: guidance({
    summary: "The normal amount expected for an occurrence; the actual invoice may differ.",
    what: "A planning amount for the obligation or each recurring due item.",
    why: "It gives users an expected financial reference before an invoice is received and supports outstanding calculations.",
    who: "The administrator using the agreement, quotation, schedule, or known recurring amount.",
    when: "Enter it when the amount is reasonably known. Update it when the underlying commercial terms change.",
    how: "Enter the expected gross amount in the selected currency. Do not overwrite it merely because one invoice differs.",
    example: "15000.00 MYR monthly rent",
  }),
  currency: guidance({
    summary: "The currency used for this obligation and its due items.",
    what: "The three-letter currency code used for expected, invoiced, requested, approved, and paid amounts.",
    why: "Amounts are meaningless without an explicit currency, especially across group entities and foreign counterparties.",
    who: "The administrator creating the record.",
    when: "Set it at creation from the agreement or billing terms.",
    how: "Use a three-letter ISO-style currency code consistently.",
    example: "MYR, SGD, USD",
  }),
  firstDueDate: guidance({
    summary: "The first occurrence expected under the obligation.",
    what: "The earliest scheduled date on which this obligation is expected to become due.",
    why: "It records the schedule origin separately from the next occurrence that still needs to be generated.",
    who: "The administrator reading the agreement or payment schedule.",
    when: "Set it when a first contractual due date is known.",
    how: "Enter the first scheduled due date from the source terms. Do not continually move it forward.",
    example: "01 Aug 2026",
  }),
  nextDueDate: guidance({
    summary: "The next scheduled occurrence that has not yet been generated into a due item.",
    what: "The operational pointer to the next recurrence Afenda should materialise.",
    why: "It lets Afenda show what is coming next without recalculating or rewriting historical due items.",
    who: "The record owner or administrator maintaining the schedule.",
    when: "Set it for recurring obligations and adjust it only when the commercial schedule changes.",
    how: "Enter the next ungenerated occurrence. When Afenda generates that due item, the pointer advances to the following occurrence.",
    example: "If August is already generated, enter 01 Sep 2026.",
  }),
  recurring: guidance({
    summary: "Turn this on when the same obligation becomes due repeatedly on a schedule.",
    what: "A flag indicating that the obligation repeats rather than occurring only once.",
    why: "It enables Afenda to generate future due items from a simple interval and unit while preserving each occurrence as history.",
    who: "The administrator creating or maintaining the schedule.",
    when: "Use it for rent, subscriptions, instalments, periodic maintenance, premiums, or similar repeating commitments.",
    how: "Turn it on, then define Repeat every, Unit, and the next due date.",
    example: "Monthly rent: recurring ON, repeat every 1 MONTH.",
  }),
  recurrenceInterval: guidance({
    summary: "How many recurrence units pass between scheduled occurrences.",
    what: "The numeric part of the repeat rule.",
    why: "Using interval plus unit covers monthly, quarterly, semi-annual, annual, weekly, and other simple schedules without a complex rule engine.",
    who: "The administrator using the agreement schedule.",
    when: "Required when Recurring is on.",
    how: "Enter a positive whole number and pair it with the correct Unit.",
    example: "Quarterly = Repeat every 3 + Unit MONTH.",
  }),
  recurrenceUnit: guidance({
    summary: "The time unit used together with Repeat every.",
    what: "The day, week, month, or year unit for the recurrence rule.",
    why: "It keeps recurring schedules understandable and avoids an unnecessary custom recurrence language in the MVP.",
    who: "The administrator maintaining the schedule.",
    when: "Required when Recurring is on.",
    how: "Choose the unit that matches the agreement, then set Repeat every to the required number.",
    example: "Every 6 MONTH = semi-annual.",
  }),
  autoRenew: guidance({
    summary: "Indicates that the arrangement renews automatically unless action is taken.",
    what: "A commercial characteristic of the agreement, not an instruction for Afenda to renew anything automatically.",
    why: "It highlights agreements where inaction can create another term or charge.",
    who: "The administrator reviewing the agreement terms.",
    when: "Turn it on only when the source agreement actually contains automatic renewal.",
    how: "Confirm the clause in the agreement and record the relevant renewal and notice dates separately.",
    example: "Annual software subscription renews automatically unless cancelled 30 days before expiry.",
  }),
  renewalDate: guidance({
    summary: "The next date the arrangement is expected to renew or enter a new term.",
    what: "The commercial renewal milestone for the obligation.",
    why: "It helps users monitor renewal decisions separately from ordinary payment due dates.",
    who: "The record owner or administrator monitoring the agreement.",
    when: "Set it when the next renewal date is known from the agreement or renewal notice.",
    how: "Use the actual renewal date, not the date by which notice must be given.",
    example: "01 Aug 2027",
  }),
  noticeDays: guidance({
    summary: "The number of days of advance notice normally required before expiry or renewal.",
    what: "The notice period stated by the agreement for termination, non-renewal, or another required action.",
    why: "It gives users the context needed to act before a renewal or expiry becomes unavoidable.",
    who: "The administrator reading the contract terms.",
    when: "Enter it whenever the agreement specifies an advance notice period.",
    how: "Record the number of calendar days required by the source agreement.",
    example: "A 90-day termination notice requirement = 90.",
  }),
  contractRequired: guidance({
    summary: "Require agreement evidence before this obligation can be activated.",
    what: "A governance control that prevents activation without a contract reference or supporting document link.",
    why: "Important obligations should not become operational records without evidence when your process requires it.",
    who: "The administrator or policy owner deciding whether evidence is mandatory for this record.",
    when: "Turn it on when the obligation should not be activated without supporting agreement evidence.",
    how: "Enable it, then provide the contract reference or document URL before activation.",
    example: "Tenancy agreement: Contract required ON.",
  }),
  contractReference: guidance({
    summary: "The agreement, policy, facility, tenancy, service, or other source reference.",
    what: "The external or internal identifier of the document that establishes the obligation.",
    why: "It lets users trace the operational record back to its source evidence quickly.",
    who: "The administrator using the signed agreement, policy, order, or approved document.",
    when: "Enter it when a source document has a meaningful reference number.",
    how: "Copy the reference exactly enough to find the source document again.",
    example: "TA-2026-081 / POL-MY-2026-01882",
  }),
  contractFileUrl: guidance({
    summary: "A link to the agreement or supporting source document.",
    what: "The storage location for the evidence supporting this obligation.",
    why: "Users can verify the record without storing document binaries inside the Corporate Administration tables.",
    who: "The administrator who has access to the approved document location.",
    when: "Add it when the document is available and keep it current if the storage location changes.",
    how: "Paste a stable authorised URL from your document storage system.",
    example: "A Google Drive, SharePoint, or approved document-management link.",
  }),
  notes: guidance({
    summary: "Operational context that does not belong in a structured field.",
    what: "Free-text notes for exceptions, clarification, follow-up context, or information useful to future administrators.",
    why: "It preserves necessary context without forcing every one-off detail into the schema.",
    who: "Any authorised administrator maintaining the record.",
    when: "Use it when information is relevant but not suitable for a standard or custom field.",
    how: "Keep notes factual, concise, and operational. Use custom fields for recurring structured information that needs filtering or reporting.",
    example: "Landlord confirmed revised billing contact effective September 2026.",
  }),
} as const;

export const COUNTERPARTY_GUIDANCE = {
  code: guidance({
    summary: "A stable internal reference for the counterparty; Afenda can generate one if blank.",
    what: "The internal code used to identify this party across obligations and later integrations.",
    why: "A stable identifier avoids relying on names, which can change or be duplicated.",
    who: "The administrator creating the counterparty.",
    when: "Set it at creation or allow Afenda to generate it.",
    how: "Use your organisation's party-coding convention if one exists.",
    example: "CP-0048",
  }),
  name: guidance({
    summary: "The legal or recognised business name of the external party.",
    what: "The party you contract with, pay, receive services from, or otherwise administer obligations with.",
    why: "This is the primary human-readable identity shown throughout Corporate Administration.",
    who: "The administrator using the agreement, invoice, registration record, or other reliable source.",
    when: "Enter it when creating the party and update it only for a genuine legal or recognised name change.",
    how: "Use the legal or billing name rather than a contact person's name.",
    example: "ABC Properties Sdn Bhd",
  }),
  type: guidance({
    summary: "The party's main operational relationship to your organisation.",
    what: "A broad classification such as vendor, landlord, service provider, insurer, financier, authority, or other.",
    why: "It improves filtering and helps users understand the party's role without creating separate party tables.",
    who: "The administrator creating the record.",
    when: "Set it at creation and revise it if the original classification was incorrect.",
    how: "Choose the closest broad type. Use custom fields when you need additional structured classification.",
    example: "LANDLORD",
  }),
  registrationNo: guidance({
    summary: "The business or organisation registration identifier, when available.",
    what: "The official registration number used to identify the legal entity.",
    why: "It helps distinguish parties with similar names and supports later verification or integration.",
    who: "The administrator using a reliable company or contract document.",
    when: "Enter it when the official number is known.",
    how: "Copy the identifier from an authoritative document; do not invent or reformat it unnecessarily.",
    example: "202001234567",
  }),
  taxId: guidance({
    summary: "The party's tax or fiscal identifier when your process needs it.",
    what: "A tax-registration identifier associated with the counterparty.",
    why: "It can support finance, tax, or later system integrations without mixing tax data into free-text notes.",
    who: "An authorised administrator using a reliable tax, invoice, or registration source.",
    when: "Enter it when available and relevant to your organisation's process.",
    how: "Use the identifier exactly as provided by the reliable source.",
    example: "Supplier tax registration number shown on the invoice.",
  }),
  defaultCurrency: guidance({
    summary: "The currency normally used with this counterparty.",
    what: "The default currency proposed when a new obligation is created for this party.",
    why: "It reduces repetitive entry while still allowing each obligation to specify its authoritative currency.",
    who: "The administrator who knows the normal commercial terms.",
    when: "Set it when there is a clear normal currency for this party.",
    how: "Use a three-letter currency code. The obligation can override it when necessary.",
    example: "MYR",
  }),
  paymentTermsDays: guidance({
    summary: "The party's normal payment term in days, used as a default reference.",
    what: "The number of days normally allowed between the relevant billing date and expected payment date.",
    why: "It records a useful commercial default without pretending every invoice or obligation has identical terms.",
    who: "The administrator or finance user using agreed commercial terms.",
    when: "Set it when a normal term is known. Specific obligations or invoices can differ.",
    how: "Enter the normal number of days as a non-negative whole number.",
    example: "30",
  }),
  isActive: guidance({
    summary: "Controls whether this party should normally be available for new administrative records.",
    what: "The operational availability state of the counterparty in Corporate Administration.",
    why: "Deactivation keeps historical links intact while preventing obsolete parties from being chosen for new work.",
    who: "An administrator responsible for maintaining party records.",
    when: "Turn it off when the party should no longer be used for new obligations, without deleting history.",
    how: "Deactivate rather than delete when the party has historical records.",
    example: "Former landlord with completed obligations: Active OFF.",
  }),
} as const;
