import { z } from "zod";

export const masterImportTargets = ["SITE", "COUNTERPARTY"] as const;
export type MasterImportTarget = (typeof masterImportTargets)[number];
export const MASTER_IMPORT_CLEAR_TOKEN = "__CLEAR__";

export const SITE_IMPORT_HEADERS = ["site_code","name","type","organization","address_line_1","address_line_2","city","state_region","postal_code","country_code","timezone","latitude","longitude","is_active","notes"] as const;
export const COUNTERPARTY_IMPORT_HEADERS = ["counterparty_code","name","type","registration_no","tax_id","contact_name","contact_email","contact_phone","address","country_code","website_url","default_currency","payment_terms_days","is_active","notes"] as const;

const siteAliases: Record<string,string> = { code:"site_code",site:"site_code",site_name:"name",site_type:"type",org:"organization",address1:"address_line_1",address2:"address_line_2",state:"state_region",postcode:"postal_code",country:"country_code",active:"is_active",remarks:"notes",remark:"notes" };
const counterpartyAliases: Record<string,string> = { code:"counterparty_code",vendor_code:"counterparty_code",supplier_code:"counterparty_code",counterparty_name:"name",vendor_name:"name",supplier_name:"name",counterparty_type:"type",registration:"registration_no",company_no:"registration_no",tin:"tax_id",email:"contact_email",phone:"contact_phone",country:"country_code",currency:"default_currency",payment_terms:"payment_terms_days",active:"is_active",remarks:"notes",remark:"notes" };

const base = { rowNumber:z.number().int().positive(), code:z.string().trim().min(2).max(50), name:z.string().trim().min(1).max(240).optional(), type:z.string().trim().min(1).max(100).optional(), isActive:z.boolean().optional(), clearFields:z.array(z.string()).default([]) };
export const siteImportRowSchema = z.object({ ...base, organization:z.string().trim().max(160).optional(), addressLine1:z.string().trim().max(500).optional(), addressLine2:z.string().trim().max(500).optional(), city:z.string().trim().max(160).optional(), stateRegion:z.string().trim().max(160).optional(), postalCode:z.string().trim().max(40).optional(), countryCode:z.string().trim().toUpperCase().regex(/^[A-Z]{2}$/).optional(), timezone:z.string().trim().max(100).optional(), latitude:z.number().min(-90).max(90).optional(), longitude:z.number().min(-180).max(180).optional(), notes:z.string().trim().max(10000).optional() }).strict();
export const counterpartyImportRowSchema = z.object({ ...base, code:z.string().trim().min(2).max(40), type:z.string().trim().min(1).max(80).optional(), registrationNo:z.string().trim().max(500).optional(), taxId:z.string().trim().max(500).optional(), contactName:z.string().trim().max(500).optional(), contactEmail:z.string().trim().email().max(320).optional(), contactPhone:z.string().trim().max(500).optional(), address:z.string().trim().max(10000).optional(), countryCode:z.string().trim().toUpperCase().regex(/^[A-Z]{2}$/).optional(), websiteUrl:z.string().trim().url().max(2000).optional(), defaultCurrency:z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/).optional(), paymentTermsDays:z.number().int().min(0).max(3650).optional(), notes:z.string().trim().max(10000).optional() }).strict();
export type SiteImportRow = z.infer<typeof siteImportRowSchema>;
export type CounterpartyImportRow = z.infer<typeof counterpartyImportRowSchema>;
export type MasterImportRow = SiteImportRow | CounterpartyImportRow;
export const masterImportPayloadSchema = z.object({ target:z.enum(masterImportTargets), rows:z.array(z.record(z.string(),z.unknown())).min(1).max(200) }).strict();
export const masterImportCommitSchema = masterImportPayloadSchema.extend({ previewHash:z.string().regex(/^[0-9a-f]{64}$/) });

function splitLine(line:string, delimiter:string){const out:string[]=[];let current="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){current+='"';i++;}else quoted=!quoted;}else if(c===delimiter&&!quoted){out.push(current.trim());current="";}else current+=c;}out.push(current.trim());return out;}
function normalize(value:string, aliases:Record<string,string>){const key=value.trim().toLowerCase().replace(/[\s-]+/g,"_");return aliases[key]??key;}
function bool(value?:string){if(!value?.trim())return undefined;const v=value.trim().toLowerCase();if(["true","yes","y","1"].includes(v))return true;if(["false","no","n","0"].includes(v))return false;throw new Error(`Invalid boolean \"${value}\"`);}
function num(value?:string){if(!value?.trim())return undefined;const n=Number(value.replaceAll(",",""));if(!Number.isFinite(n))throw new Error(`Invalid number \"${value}\"`);return n;}
function isClear(value?:string){return value?.trim().toUpperCase()===MASTER_IMPORT_CLEAR_TOKEN;}

export function masterImportTemplate(target:MasterImportTarget):string { const headers=target==="SITE"?SITE_IMPORT_HEADERS:COUNTERPARTY_IMPORT_HEADERS; return headers.join("\t"); }

export function parseMasterImportText(target:MasterImportTarget,text:string):{rows:MasterImportRow[];errors:string[]}{
  const normalized=text.replaceAll("\r\n","\n").replaceAll("\r","\n").trim(); if(!normalized)return{rows:[],errors:["Paste or load a table first."]}; const lines=normalized.split("\n").filter(l=>l.trim()); if(lines.length<2)return{rows:[],errors:["Include a header row and at least one data row."]};
  const delimiter=lines[0].includes("\t")?"\t":","; const allowed=(target==="SITE"?SITE_IMPORT_HEADERS:COUNTERPARTY_IMPORT_HEADERS) as readonly string[]; const aliases=target==="SITE"?siteAliases:counterpartyAliases; const idHeader=target==="SITE"?"site_code":"counterparty_code"; const headers=splitLine(lines[0],delimiter).map(h=>normalize(h,aliases));
  if(!headers.includes(idHeader))return{rows:[],errors:[`Missing required column: ${idHeader}`]}; const unknown=headers.filter(h=>h&&!allowed.includes(h)); if(unknown.length)return{rows:[],errors:[`Unknown column${unknown.length===1?"":"s"}: ${unknown.join(", ")}`]}; const duplicates=[...new Set(headers.filter((h,i)=>h&&headers.indexOf(h)!==i))]; if(duplicates.length)return{rows:[],errors:[`Multiple columns map to the same Afenda field: ${duplicates.join(", ")}`]};
  const rows:MasterImportRow[]=[],errors:string[]=[];
  for(let index=1;index<lines.length;index++){const cells=splitLine(lines[index],delimiter);const source=Object.fromEntries(headers.map((h,i)=>[h,cells[i]??""]));try{
    if(target==="SITE"){
      const clearFields:string[]=[]; const clearMap:Record<string,string>={organization:"organization",address_line_1:"addressLine1",address_line_2:"addressLine2",city:"city",state_region:"stateRegion",postal_code:"postalCode",country_code:"countryCode",timezone:"timezone",latitude:"latitude",longitude:"longitude",notes:"notes"}; for(const [header,field] of Object.entries(clearMap))if(isClear(source[header]))clearFields.push(field); for(const header of ["site_code","name","type","is_active"])if(isClear(source[header]))throw new Error(`${MASTER_IMPORT_CLEAR_TOKEN} is not allowed for ${header}`); const v=(h:string)=>isClear(source[h])?undefined:source[h]; const parsed=siteImportRowSchema.safeParse({rowNumber:index+1,code:source.site_code,name:v("name")||undefined,type:v("type")||undefined,organization:v("organization")||undefined,addressLine1:v("address_line_1")||undefined,addressLine2:v("address_line_2")||undefined,city:v("city")||undefined,stateRegion:v("state_region")||undefined,postalCode:v("postal_code")||undefined,countryCode:v("country_code")||undefined,timezone:v("timezone")||undefined,latitude:num(v("latitude")),longitude:num(v("longitude")),isActive:bool(v("is_active")),notes:v("notes")||undefined,clearFields}); if(!parsed.success)errors.push(`Row ${index+1}: ${parsed.error.issues.map(i=>i.message).join("; ")}`);else rows.push(parsed.data);
    }else{
      const clearFields:string[]=[]; const clearMap:Record<string,string>={registration_no:"registrationNo",tax_id:"taxId",contact_name:"contactName",contact_email:"contactEmail",contact_phone:"contactPhone",address:"address",country_code:"countryCode",website_url:"websiteUrl",default_currency:"defaultCurrency",payment_terms_days:"paymentTermsDays",notes:"notes"}; for(const [header,field] of Object.entries(clearMap))if(isClear(source[header]))clearFields.push(field); for(const header of ["counterparty_code","name","type","is_active"])if(isClear(source[header]))throw new Error(`${MASTER_IMPORT_CLEAR_TOKEN} is not allowed for ${header}`); const v=(h:string)=>isClear(source[h])?undefined:source[h]; const parsed=counterpartyImportRowSchema.safeParse({rowNumber:index+1,code:source.counterparty_code,name:v("name")||undefined,type:v("type")||undefined,registrationNo:v("registration_no")||undefined,taxId:v("tax_id")||undefined,contactName:v("contact_name")||undefined,contactEmail:v("contact_email")||undefined,contactPhone:v("contact_phone")||undefined,address:v("address")||undefined,countryCode:v("country_code")||undefined,websiteUrl:v("website_url")||undefined,defaultCurrency:v("default_currency")||undefined,paymentTermsDays:num(v("payment_terms_days")),isActive:bool(v("is_active")),notes:v("notes")||undefined,clearFields}); if(!parsed.success)errors.push(`Row ${index+1}: ${parsed.error.issues.map(i=>i.message).join("; ")}`);else rows.push(parsed.data);
    }
  }catch(error){errors.push(`Row ${index+1}: ${error instanceof Error?error.message:"Could not parse row"}`);}}
  return{rows,errors};
}
