import { createHash } from "node:crypto";

import type { Prisma } from "@/generated/prisma/client";
import { audit } from "@/lib/audit";
import { cleanOptionalString, createCounterpartySchema, createSiteSchema } from "@/lib/corporate-admin/domain";
import { counterpartyImportRowSchema, siteImportRowSchema, type CounterpartyImportRow, type MasterImportTarget, type SiteImportRow } from "@/lib/corporate-admin/master-import";
import { db } from "@/lib/db";

type DbClient = Prisma.TransactionClient | typeof db;
export type MasterImportChange = { field:string; before:string|number|boolean|null; after:string|number|boolean|null; destructive?:boolean };
export type MasterImportPreviewRow = { rowNumber:number; code:string; action:"CREATE"|"UPDATE"|"NO_CHANGE"|"ERROR"; recordId:string|null; changes:MasterImportChange[]; errors:string[] };
export type MasterImportPlan = { target:MasterImportTarget; rows:MasterImportPreviewRow[]; previewHash:string; summary:{create:number;update:number;noChange:number;error:number;clears:number} };

function comparable(value:unknown):string|number|boolean|null{if(value==null)return null;if(typeof value==="string"||typeof value==="number"||typeof value==="boolean")return value;return Number.isNaN(Number(value))?String(value):Number(value);}
function applyClears<T extends Record<string,unknown>>(current:T,row:Record<string,unknown>,clearFields:string[]){const out={...current};for(const [key,value] of Object.entries(row))if(!["rowNumber","code","clearFields"].includes(key)&&value!==undefined)out[key]=value;for(const field of clearFields)out[field]=null;return out;}

function siteCurrent(record:{name:string;type:string;organization:string|null;addressLine1:string|null;addressLine2:string|null;city:string|null;stateRegion:string|null;postalCode:string|null;countryCode:string|null;timezone:string|null;latitude:{toString():string}|number|null;longitude:{toString():string}|number|null;isActive:boolean;notes:string|null}){return{name:record.name,type:record.type,organization:record.organization,addressLine1:record.addressLine1,addressLine2:record.addressLine2,city:record.city,stateRegion:record.stateRegion,postalCode:record.postalCode,countryCode:record.countryCode,timezone:record.timezone,latitude:record.latitude==null?null:Number(record.latitude.toString()),longitude:record.longitude==null?null:Number(record.longitude.toString()),isActive:record.isActive,notes:record.notes};}
function counterpartyCurrent(record:{name:string;type:string;registrationNo:string|null;taxId:string|null;contactName:string|null;contactEmail:string|null;contactPhone:string|null;address:string|null;countryCode:string|null;websiteUrl:string|null;defaultCurrency:string|null;paymentTermsDays:number|null;isActive:boolean;notes:string|null}){return{name:record.name,type:record.type,registrationNo:record.registrationNo,taxId:record.taxId,contactName:record.contactName,contactEmail:record.contactEmail,contactPhone:record.contactPhone,address:record.address,countryCode:record.countryCode,websiteUrl:record.websiteUrl,defaultCurrency:record.defaultCurrency,paymentTermsDays:record.paymentTermsDays,isActive:record.isActive,notes:record.notes};}

export async function buildMasterImportPlan(target:MasterImportTarget,rawRows:Record<string,unknown>[],client:DbClient=db):Promise<MasterImportPlan>{
  const parsedRows = target==="SITE" ? rawRows.map(r=>siteImportRowSchema.parse(r)) : rawRows.map(r=>counterpartyImportRowSchema.parse(r));
  const codes=[...new Set(parsedRows.map(r=>r.code.toUpperCase()))];
  const records=target==="SITE"
    ? await client.administrativeSite.findMany({where:{code:{in:codes}},select:{id:true,code:true,name:true,type:true,organization:true,addressLine1:true,addressLine2:true,city:true,stateRegion:true,postalCode:true,countryCode:true,timezone:true,latitude:true,longitude:true,isActive:true,notes:true}})
    : await client.administrativeCounterparty.findMany({where:{code:{in:codes}},select:{id:true,code:true,name:true,type:true,registrationNo:true,taxId:true,contactName:true,contactEmail:true,contactPhone:true,address:true,countryCode:true,websiteUrl:true,defaultCurrency:true,paymentTermsDays:true,isActive:true,notes:true}});
  const byCode=new Map(records.map(r=>[r.code.toUpperCase(),r])); const seen=new Set<string>(); const previewRows:MasterImportPreviewRow[]=[];
  for(const raw of parsedRows){const code=raw.code.toUpperCase();const errors:string[]=[];if(seen.has(code))errors.push(`Duplicate ${target.toLowerCase()} code in this import`);seen.add(code);const record=byCode.get(code);let current:Record<string,unknown>|undefined;let merged:Record<string,unknown>;
    if(target==="SITE"){current=record?siteCurrent(record as never):undefined;const row=raw as SiteImportRow;merged=applyClears(current??{name:undefined,type:undefined,organization:null,addressLine1:null,addressLine2:null,city:null,stateRegion:null,postalCode:null,countryCode:null,timezone:null,latitude:null,longitude:null,isActive:true,notes:null},row as unknown as Record<string,unknown>,row.clearFields);const validation=createSiteSchema.safeParse({code,...merged,customFields:{}});if(!validation.success)errors.push(...validation.error.issues.map(i=>`${i.path.join(".")||"site"}: ${i.message}`));}
    else{current=record?counterpartyCurrent(record as never):undefined;const row=raw as CounterpartyImportRow;merged=applyClears(current??{name:undefined,type:undefined,registrationNo:null,taxId:null,contactName:null,contactEmail:null,contactPhone:null,address:null,countryCode:null,websiteUrl:null,defaultCurrency:null,paymentTermsDays:null,isActive:true,notes:null},row as unknown as Record<string,unknown>,row.clearFields);const validation=createCounterpartySchema.safeParse({code,...merged,customFields:{}});if(!validation.success)errors.push(...validation.error.issues.map(i=>`${i.path.join(".")||"counterparty"}: ${i.message}`));}
    const changes:MasterImportChange[]=[];for(const [field,afterRaw] of Object.entries(merged)){if(field==="code")continue;const before=comparable(current?.[field]);const after=comparable(afterRaw);if(before!==after)changes.push({field,before,after,destructive:(raw.clearFields??[]).includes(field)});}
    previewRows.push({rowNumber:raw.rowNumber,code,action:errors.length?"ERROR":record?(changes.length?"UPDATE":"NO_CHANGE"):"CREATE",recordId:record?.id??null,changes,errors});
  }
  const canonical=previewRows.map(r=>({rowNumber:r.rowNumber,code:r.code,action:r.action,recordId:r.recordId,changes:r.changes,errors:r.errors}));const previewHash=createHash("sha256").update(JSON.stringify(canonical)).digest("hex");const summary={create:previewRows.filter(r=>r.action==="CREATE").length,update:previewRows.filter(r=>r.action==="UPDATE").length,noChange:previewRows.filter(r=>r.action==="NO_CHANGE").length,error:previewRows.filter(r=>r.action==="ERROR").length,clears:previewRows.reduce((n,r)=>n+r.changes.filter(c=>c.destructive).length,0)};return{target,rows:previewRows,previewHash,summary};
}

export async function applyMasterImport(target:MasterImportTarget,rawRows:Record<string,unknown>[],actorId:string,expectedPreviewHash:string){return db.$transaction(async tx=>{const plan=await buildMasterImportPlan(target,rawRows,tx);if(plan.previewHash!==expectedPreviewHash)throw new Error("Import preview is stale. Preview again before committing.");if(plan.summary.error)throw new Error("Import contains validation errors. Resolve them before committing.");let created=0,updated=0;
  for(const raw of rawRows){const preview=plan.rows.find(r=>r.rowNumber===Number(raw.rowNumber))!;if(preview.action==="NO_CHANGE")continue;
    if(target==="SITE"){const row=siteImportRowSchema.parse(raw);const existing=preview.recordId?await tx.administrativeSite.findUnique({where:{id:preview.recordId},select:{name:true,type:true,organization:true,addressLine1:true,addressLine2:true,city:true,stateRegion:true,postalCode:true,countryCode:true,timezone:true,latitude:true,longitude:true,isActive:true,notes:true}}):null;const merged=applyClears(existing?siteCurrent(existing):{name:undefined,type:undefined,organization:null,addressLine1:null,addressLine2:null,city:null,stateRegion:null,postalCode:null,countryCode:null,timezone:null,latitude:null,longitude:null,isActive:true,notes:null},row as unknown as Record<string,unknown>,row.clearFields);const parsed=createSiteSchema.parse({code:row.code,...merged,customFields:{}});const data={code:row.code.toUpperCase(),name:parsed.name,type:parsed.type,organization:cleanOptionalString(parsed.organization),addressLine1:cleanOptionalString(parsed.addressLine1),addressLine2:cleanOptionalString(parsed.addressLine2),city:cleanOptionalString(parsed.city),stateRegion:cleanOptionalString(parsed.stateRegion),postalCode:cleanOptionalString(parsed.postalCode),countryCode:cleanOptionalString(parsed.countryCode)?.toUpperCase()??null,timezone:cleanOptionalString(parsed.timezone),latitude:parsed.latitude??null,longitude:parsed.longitude??null,isActive:parsed.isActive,notes:cleanOptionalString(parsed.notes)};const record=preview.recordId?await tx.administrativeSite.update({where:{id:preview.recordId},data}):await tx.administrativeSite.create({data:{...data,customFields:{}}});await audit(actorId,preview.recordId?"corporate.site.updated":"corporate.site.created",record.id,{siteId:record.id,source:"safe_import",clears:row.clearFields.length},tx);if(preview.recordId)updated++;else created++;}
    else{const row=counterpartyImportRowSchema.parse(raw);const existing=preview.recordId?await tx.administrativeCounterparty.findUnique({where:{id:preview.recordId},select:{name:true,type:true,registrationNo:true,taxId:true,contactName:true,contactEmail:true,contactPhone:true,address:true,countryCode:true,websiteUrl:true,defaultCurrency:true,paymentTermsDays:true,isActive:true,notes:true}}):null;const merged=applyClears(existing?counterpartyCurrent(existing):{name:undefined,type:undefined,registrationNo:null,taxId:null,contactName:null,contactEmail:null,contactPhone:null,address:null,countryCode:null,websiteUrl:null,defaultCurrency:null,paymentTermsDays:null,isActive:true,notes:null},row as unknown as Record<string,unknown>,row.clearFields);const parsed=createCounterpartySchema.parse({code:row.code,...merged,customFields:{}});const data={code:row.code.toUpperCase(),name:parsed.name,type:parsed.type,registrationNo:cleanOptionalString(parsed.registrationNo),taxId:cleanOptionalString(parsed.taxId),contactName:cleanOptionalString(parsed.contactName),contactEmail:cleanOptionalString(parsed.contactEmail),contactPhone:cleanOptionalString(parsed.contactPhone),address:cleanOptionalString(parsed.address),countryCode:cleanOptionalString(parsed.countryCode),websiteUrl:cleanOptionalString(parsed.websiteUrl),defaultCurrency:cleanOptionalString(parsed.defaultCurrency)?.toUpperCase()??null,paymentTermsDays:parsed.paymentTermsDays??null,isActive:parsed.isActive,notes:cleanOptionalString(parsed.notes)};const record=preview.recordId?await tx.administrativeCounterparty.update({where:{id:preview.recordId},data}):await tx.administrativeCounterparty.create({data:{...data,customFields:{}}});await audit(actorId,preview.recordId?"corporate.counterparty.updated":"corporate.counterparty.created",record.id,{counterpartyId:record.id,source:"safe_import",clears:row.clearFields.length},tx);if(preview.recordId)updated++;else created++;}
  }
  return{target,created,updated,noChange:plan.summary.noChange,clears:plan.summary.clears};});}
