import { createHash } from "node:crypto";

import type { Prisma } from "@/generated/prisma/client";
import { audit } from "@/lib/audit";
import { cleanOptionalString, parseDateOnly } from "@/lib/corporate-admin/domain";
import {
  contactImportRowSchema, coverageImportRowSchema, obligationPartyImportRowSchema, obligationSiteImportRowSchema,
  type RelationalImportTarget,
} from "@/lib/corporate-admin/relational-import";
import { db } from "@/lib/db";

type DbClient = Prisma.TransactionClient | typeof db;
export type RelationalImportChange = { field:string; before:string|boolean|null; after:string|boolean|null };
export type RelationalImportPreviewRow = { rowNumber:number; key:string; action:"CREATE"|"UPDATE"|"NO_CHANGE"|"CONFLICT"|"ERROR"; recordId:string|null; changes:RelationalImportChange[]; errors:string[] };
export type RelationalImportPlan = { target:RelationalImportTarget; rows:RelationalImportPreviewRow[]; previewHash:string; summary:{create:number;update:number;noChange:number;conflict:number;error:number} };

function comparable(value:unknown):string|boolean|null{if(value==null)return null;if(typeof value==="boolean"||typeof value==="string")return value;if(value instanceof Date)return value.toISOString().slice(0,10);return String(value);}
function changes(current:Record<string,unknown>|undefined,next:Record<string,unknown>):RelationalImportChange[]{const out:RelationalImportChange[]=[];for(const [field,afterRaw] of Object.entries(next)){if(afterRaw===undefined)continue;const before=comparable(current?.[field]),after=comparable(afterRaw);if(before!==after)out.push({field,before,after});}return out;}
function finish(target:RelationalImportTarget,rows:RelationalImportPreviewRow[]):RelationalImportPlan{const canonical=rows.map(r=>({rowNumber:r.rowNumber,key:r.key,action:r.action,recordId:r.recordId,changes:r.changes,errors:r.errors}));return{target,rows,previewHash:createHash("sha256").update(JSON.stringify(canonical)).digest("hex"),summary:{create:rows.filter(r=>r.action==="CREATE").length,update:rows.filter(r=>r.action==="UPDATE").length,noChange:rows.filter(r=>r.action==="NO_CHANGE").length,conflict:rows.filter(r=>r.action==="CONFLICT").length,error:rows.filter(r=>r.action==="ERROR").length}};}

async function contactPlan(rawRows:Record<string,unknown>[],client:DbClient){
  const rows=rawRows.map(r=>contactImportRowSchema.parse(r));const cpCodes=[...new Set(rows.map(r=>r.counterpartyCode.toUpperCase()))];const cps=await client.administrativeCounterparty.findMany({where:{code:{in:cpCodes}},select:{id:true,code:true,isActive:true,contacts:{select:{id:true,name:true,email:true,jobTitle:true,department:true,phone:true,mobile:true,role:true,isPrimary:true,isActive:true,notes:true}}}});const cpMap=new Map(cps.map(c=>[c.code.toUpperCase(),c]));const seen=new Set<string>();const preview:RelationalImportPreviewRow[]=[];
  for(const row of rows){const cp=cpMap.get(row.counterpartyCode.toUpperCase());const key=`${row.counterpartyCode.toUpperCase()}::${row.email.toLowerCase()}`;const errors:string[]=[];if(seen.has(key))errors.push("Duplicate counterparty_code + email in this import");seen.add(key);if(!cp)errors.push(`Counterparty ${row.counterpartyCode.toUpperCase()} was not found`);else if(!cp.isActive)errors.push("Inactive counterparties cannot receive imported active contacts");const matches=cp?.contacts.filter(c=>c.email?.toLowerCase()===row.email.toLowerCase())??[];if(matches.length>1)errors.push("Multiple existing contacts match this counterparty + email");const record=matches[0];if(row.isPrimary&&cp){const otherPrimary=cp.contacts.find(c=>c.isPrimary&&c.id!==record?.id);if(otherPrimary)errors.push("Another primary contact already exists for this counterparty");}const next={name:row.contactName,email:row.email,jobTitle:row.jobTitle,department:row.department,phone:row.phone,mobile:row.mobile,role:row.role,isPrimary:row.isPrimary??record?.isPrimary??false,isActive:row.isActive??record?.isActive??true,notes:row.notes};const current=record?{name:record.name,email:record.email,jobTitle:record.jobTitle,department:record.department,phone:record.phone,mobile:record.mobile,role:record.role,isPrimary:record.isPrimary,isActive:record.isActive,notes:record.notes}:undefined;const diff=changes(current,next);const conflict=errors.some(e=>e.startsWith("Multiple")||e.startsWith("Another primary"));preview.push({rowNumber:row.rowNumber,key,action:errors.length?(conflict?"CONFLICT":"ERROR"):record?(diff.length?"UPDATE":"NO_CHANGE"):"CREATE",recordId:record?.id??null,changes:diff,errors});}
  return finish("CONTACT",preview);
}

async function coveragePlan(rawRows:Record<string,unknown>[],client:DbClient){
  const rows=rawRows.map(r=>coverageImportRowSchema.parse(r));const siteCodes=[...new Set(rows.map(r=>r.siteCode.toUpperCase()))],cpCodes=[...new Set(rows.map(r=>r.counterpartyCode.toUpperCase()))];const [sites,cps]=await Promise.all([client.administrativeSite.findMany({where:{code:{in:siteCodes}},select:{id:true,code:true,isActive:true,serviceCoverage:{select:{id:true,counterpartyId:true,serviceCategory:true,roleCode:true,effectiveFrom:true,effectiveTo:true,isPrimary:true,isActive:true,serviceLevel:true,emergencyContact:true,notes:true}}}}),client.administrativeCounterparty.findMany({where:{code:{in:cpCodes}},select:{id:true,code:true,isActive:true}})]);const siteMap=new Map(sites.map(s=>[s.code.toUpperCase(),s])),cpMap=new Map(cps.map(c=>[c.code.toUpperCase(),c]));const seen=new Set<string>();const preview:RelationalImportPreviewRow[]=[];
  for(const row of rows){const site=siteMap.get(row.siteCode.toUpperCase()),cp=cpMap.get(row.counterpartyCode.toUpperCase());const role=(row.roleCode??"").toUpperCase();const key=`${row.siteCode.toUpperCase()}::${row.counterpartyCode.toUpperCase()}::${row.serviceCategory.toUpperCase()}::${role}`;const errors:string[]=[];if(seen.has(key))errors.push("Duplicate service-coverage natural key in this import");seen.add(key);if(!site)errors.push(`Site ${row.siteCode.toUpperCase()} was not found`);else if(!site.isActive)errors.push("Inactive Sites cannot receive active service coverage");if(!cp)errors.push(`Counterparty ${row.counterpartyCode.toUpperCase()} was not found`);else if(!cp.isActive)errors.push("Inactive counterparties cannot receive active service coverage");const matches=site&&cp?site.serviceCoverage.filter(c=>c.counterpartyId===cp.id&&c.serviceCategory.toUpperCase()===row.serviceCategory.toUpperCase()&&(c.roleCode??"").toUpperCase()===role):[];if((matches?.length??0)>1)errors.push("Multiple existing service-coverage rows match this natural key");const record=matches?.[0];if(row.isPrimary&&site){const competing=site.serviceCoverage.find(c=>c.isActive&&c.isPrimary&&c.serviceCategory.toUpperCase()===row.serviceCategory.toUpperCase()&&c.id!==record?.id);if(competing)errors.push("Another active primary provider already exists for this Site + service category");}const next={serviceCategory:row.serviceCategory.toUpperCase(),roleCode:row.roleCode,effectiveFrom:row.effectiveFrom,effectiveTo:row.effectiveTo,isPrimary:row.isPrimary??record?.isPrimary??false,isActive:row.isActive??record?.isActive??true,serviceLevel:row.serviceLevel,emergencyContact:row.emergencyContact,notes:row.notes};const current=record?{serviceCategory:record.serviceCategory,roleCode:record.roleCode,effectiveFrom:record.effectiveFrom,effectiveTo:record.effectiveTo,isPrimary:record.isPrimary,isActive:record.isActive,serviceLevel:record.serviceLevel,emergencyContact:record.emergencyContact,notes:record.notes}:undefined;const diff=changes(current,next);const conflict=errors.some(e=>e.startsWith("Multiple")||e.startsWith("Another active primary"));preview.push({rowNumber:row.rowNumber,key,action:errors.length?(conflict?"CONFLICT":"ERROR"):record?(diff.length?"UPDATE":"NO_CHANGE"):"CREATE",recordId:record?.id??null,changes:diff,errors});}
  return finish("SERVICE_COVERAGE",preview);
}

async function obligationSitePlan(rawRows:Record<string,unknown>[],client:DbClient){
  const rows=rawRows.map(r=>obligationSiteImportRowSchema.parse(r));const oCodes=[...new Set(rows.map(r=>r.obligationCode.toUpperCase()))],sCodes=[...new Set(rows.map(r=>r.siteCode.toUpperCase()))];const [obs,sites]=await Promise.all([client.administrativeObligation.findMany({where:{code:{in:oCodes}},select:{id:true,code:true,status:true,sites:{select:{siteId:true,scopeRole:true,notes:true}}}}),client.administrativeSite.findMany({where:{code:{in:sCodes}},select:{id:true,code:true,isActive:true}})]);const oMap=new Map(obs.map(o=>[o.code.toUpperCase(),o])),sMap=new Map(sites.map(s=>[s.code.toUpperCase(),s]));const seen=new Set<string>();const preview:RelationalImportPreviewRow[]=[];
  for(const row of rows){const ob=oMap.get(row.obligationCode.toUpperCase()),site=sMap.get(row.siteCode.toUpperCase());const key=`${row.obligationCode.toUpperCase()}::${row.siteCode.toUpperCase()}`;const errors:string[]=[];if(seen.has(key))errors.push("Duplicate obligation_code + site_code in this import");seen.add(key);if(!ob)errors.push(`Obligation ${row.obligationCode.toUpperCase()} was not found`);if(!site)errors.push(`Site ${row.siteCode.toUpperCase()} was not found`);else if(!site.isActive)errors.push("Inactive Sites cannot be newly linked");const record=ob&&site?ob.sites.find(s=>s.siteId===site.id):undefined;const next={scopeRole:row.scopeRole,notes:row.notes};const current=record?{scopeRole:record.scopeRole,notes:record.notes}:undefined;const diff=changes(current,next);preview.push({rowNumber:row.rowNumber,key,action:errors.length?"ERROR":record?(diff.length?"UPDATE":"NO_CHANGE"):"CREATE",recordId:record?key:null,changes:diff,errors});}
  return finish("OBLIGATION_SITE",preview);
}

async function obligationPartyPlan(rawRows:Record<string,unknown>[],client:DbClient){
  const rows=rawRows.map(r=>obligationPartyImportRowSchema.parse(r));const oCodes=[...new Set(rows.map(r=>r.obligationCode.toUpperCase()))],cCodes=[...new Set(rows.map(r=>r.counterpartyCode.toUpperCase()))];const [obs,cps]=await Promise.all([client.administrativeObligation.findMany({where:{code:{in:oCodes}},select:{id:true,code:true,status:true,parties:{select:{counterpartyId:true,roleCode:true,isPrimary:true,effectiveFrom:true,effectiveTo:true,notes:true}}}}),client.administrativeCounterparty.findMany({where:{code:{in:cCodes}},select:{id:true,code:true,isActive:true}})]);const oMap=new Map(obs.map(o=>[o.code.toUpperCase(),o])),cMap=new Map(cps.map(c=>[c.code.toUpperCase(),c]));const seen=new Set<string>();const preview:RelationalImportPreviewRow[]=[];
  for(const row of rows){const ob=oMap.get(row.obligationCode.toUpperCase()),cp=cMap.get(row.counterpartyCode.toUpperCase());const key=`${row.obligationCode.toUpperCase()}::${row.counterpartyCode.toUpperCase()}::${row.roleCode.toUpperCase()}`;const errors:string[]=[];if(seen.has(key))errors.push("Duplicate obligation-party natural key in this import");seen.add(key);if(!ob)errors.push(`Obligation ${row.obligationCode.toUpperCase()} was not found`);if(!cp)errors.push(`Counterparty ${row.counterpartyCode.toUpperCase()} was not found`);else if(!cp.isActive)errors.push("Inactive counterparties cannot receive new obligation roles");const record=ob&&cp?ob.parties.find(p=>p.counterpartyId===cp.id&&p.roleCode.toUpperCase()===row.roleCode.toUpperCase()):undefined;if(row.isPrimary&&ob){const competing=ob.parties.find(p=>p.isPrimary&&(p.counterpartyId!==cp?.id||p.roleCode.toUpperCase()!==row.roleCode.toUpperCase()));if(competing)errors.push("Another primary obligation party already exists");}const next={isPrimary:row.isPrimary??record?.isPrimary??false,effectiveFrom:row.effectiveFrom,effectiveTo:row.effectiveTo,notes:row.notes};const current=record?{isPrimary:record.isPrimary,effectiveFrom:record.effectiveFrom,effectiveTo:record.effectiveTo,notes:record.notes}:undefined;const diff=changes(current,next);const conflict=errors.some(e=>e.startsWith("Another primary"));preview.push({rowNumber:row.rowNumber,key,action:errors.length?(conflict?"CONFLICT":"ERROR"):record?(diff.length?"UPDATE":"NO_CHANGE"):"CREATE",recordId:record?key:null,changes:diff,errors});}
  return finish("OBLIGATION_PARTY",preview);
}

export async function buildRelationalImportPlan(target:RelationalImportTarget,rawRows:Record<string,unknown>[],client:DbClient=db):Promise<RelationalImportPlan>{if(target==="CONTACT")return contactPlan(rawRows,client);if(target==="SERVICE_COVERAGE")return coveragePlan(rawRows,client);if(target==="OBLIGATION_SITE")return obligationSitePlan(rawRows,client);return obligationPartyPlan(rawRows,client);}

export async function applyRelationalImport(target:RelationalImportTarget,rawRows:Record<string,unknown>[],actorId:string,expectedPreviewHash:string){return db.$transaction(async tx=>{const plan=await buildRelationalImportPlan(target,rawRows,tx);if(plan.previewHash!==expectedPreviewHash)throw new Error("Import preview is stale. Preview again before committing.");if(plan.summary.error||plan.summary.conflict)throw new Error("Import contains errors or conflicts. Resolve them before committing.");let created=0,updated=0;
  if(target==="CONTACT"){for(const raw of rawRows){const row=contactImportRowSchema.parse(raw),preview=plan.rows.find(r=>r.rowNumber===row.rowNumber)!;if(preview.action==="NO_CHANGE")continue;const cp=await tx.administrativeCounterparty.findUniqueOrThrow({where:{code:row.counterpartyCode.toUpperCase()},select:{id:true}});const data={name:row.contactName,email:row.email.toLowerCase(),jobTitle:cleanOptionalString(row.jobTitle),department:cleanOptionalString(row.department),phone:cleanOptionalString(row.phone),mobile:cleanOptionalString(row.mobile),role:cleanOptionalString(row.role),isPrimary:row.isPrimary??false,isActive:row.isActive??true,notes:cleanOptionalString(row.notes)};const record=preview.recordId?await tx.administrativeCounterpartyContact.update({where:{id:preview.recordId},data}):await tx.administrativeCounterpartyContact.create({data:{counterpartyId:cp.id,...data}});await audit(actorId,preview.recordId?"corporate.counterparty.contact.updated":"corporate.counterparty.contact.created",record.id,{counterpartyId:cp.id,source:"relational_import"},tx);if(preview.recordId)updated+=1;else created+=1;}}
  else if(target==="SERVICE_COVERAGE"){for(const raw of rawRows){const row=coverageImportRowSchema.parse(raw),preview=plan.rows.find(r=>r.rowNumber===row.rowNumber)!;if(preview.action==="NO_CHANGE")continue;const [site,cp]=await Promise.all([tx.administrativeSite.findUniqueOrThrow({where:{code:row.siteCode.toUpperCase()},select:{id:true}}),tx.administrativeCounterparty.findUniqueOrThrow({where:{code:row.counterpartyCode.toUpperCase()},select:{id:true}})]);const data={serviceCategory:row.serviceCategory.toUpperCase(),roleCode:cleanOptionalString(row.roleCode),effectiveFrom:row.effectiveFrom?parseDateOnly(row.effectiveFrom):null,effectiveTo:row.effectiveTo?parseDateOnly(row.effectiveTo):null,isPrimary:row.isPrimary??false,isActive:row.isActive??true,serviceLevel:cleanOptionalString(row.serviceLevel),emergencyContact:cleanOptionalString(row.emergencyContact),notes:cleanOptionalString(row.notes)};const record=preview.recordId?await tx.administrativeServiceCoverage.update({where:{id:preview.recordId},data}):await tx.administrativeServiceCoverage.create({data:{siteId:site.id,counterpartyId:cp.id,...data}});await audit(actorId,preview.recordId?"corporate.site.coverage.updated":"corporate.site.coverage.created",record.id,{siteId:site.id,counterpartyId:cp.id,serviceCategory:record.serviceCategory,source:"relational_import"},tx);if(preview.recordId)updated+=1;else created+=1;}}
  else if(target==="OBLIGATION_SITE"){for(const raw of rawRows){const row=obligationSiteImportRowSchema.parse(raw),preview=plan.rows.find(r=>r.rowNumber===row.rowNumber)!;if(preview.action==="NO_CHANGE")continue;const [ob,site]=await Promise.all([tx.administrativeObligation.findUniqueOrThrow({where:{code:row.obligationCode.toUpperCase()},select:{id:true}}),tx.administrativeSite.findUniqueOrThrow({where:{code:row.siteCode.toUpperCase()},select:{id:true}})]);const exists=await tx.administrativeObligationSite.findUnique({where:{obligationId_siteId:{obligationId:ob.id,siteId:site.id}}});await tx.administrativeObligationSite.upsert({where:{obligationId_siteId:{obligationId:ob.id,siteId:site.id}},update:{scopeRole:cleanOptionalString(row.scopeRole),notes:cleanOptionalString(row.notes)},create:{obligationId:ob.id,siteId:site.id,scopeRole:cleanOptionalString(row.scopeRole),notes:cleanOptionalString(row.notes)}});await audit(actorId,"corporate.obligation.site.linked",ob.id,{siteId:site.id,source:"relational_import",updated:Boolean(exists)},tx);if(exists)updated+=1;else created+=1;}}
  else {for(const raw of rawRows){const row=obligationPartyImportRowSchema.parse(raw),preview=plan.rows.find(r=>r.rowNumber===row.rowNumber)!;if(preview.action==="NO_CHANGE")continue;const [ob,cp]=await Promise.all([tx.administrativeObligation.findUniqueOrThrow({where:{code:row.obligationCode.toUpperCase()},select:{id:true}}),tx.administrativeCounterparty.findUniqueOrThrow({where:{code:row.counterpartyCode.toUpperCase()},select:{id:true}})]);const where={obligationId_counterpartyId_roleCode:{obligationId:ob.id,counterpartyId:cp.id,roleCode:row.roleCode.toUpperCase()}};const exists=await tx.administrativeObligationParty.findUnique({where});await tx.administrativeObligationParty.upsert({where,update:{isPrimary:row.isPrimary??false,effectiveFrom:row.effectiveFrom?parseDateOnly(row.effectiveFrom):null,effectiveTo:row.effectiveTo?parseDateOnly(row.effectiveTo):null,notes:cleanOptionalString(row.notes)},create:{obligationId:ob.id,counterpartyId:cp.id,roleCode:row.roleCode.toUpperCase(),isPrimary:row.isPrimary??false,effectiveFrom:row.effectiveFrom?parseDateOnly(row.effectiveFrom):null,effectiveTo:row.effectiveTo?parseDateOnly(row.effectiveTo):null,notes:cleanOptionalString(row.notes)}});await audit(actorId,"corporate.obligation.party.linked",ob.id,{counterpartyId:cp.id,roleCode:row.roleCode.toUpperCase(),source:"relational_import",updated:Boolean(exists)},tx);if(exists)updated+=1;else created+=1;}}
  return{target,created,updated,noChange:plan.summary.noChange};});}
