import type { AfendaGuidance } from "@/lib/afenda-guidance";

export const DUE_ITEM_GUIDANCE: Record<
  "periodLabel" | "dueDate" | "expectedAmount" | "invoiceAmount" | "currency" | "invoiceNumber" | "invoiceFileUrl" | "invoiceRequired" | "disputeFlag" | "notes",
  AfendaGuidance
> = {
  periodLabel: {
    summary: "A human-readable name for the billing or obligation occurrence.",
    what: "The label that identifies this specific due occurrence within its parent obligation.",
    why: "It lets users distinguish monthly, quarterly, annual, deposit, ad-hoc, or exceptional due items without decoding dates.",
    who: "The administrator generating or maintaining the due item.",
    when: "Set when the due item is created and revise only if the original label was misleading.",
    how: "Use the period or purpose users will recognise immediately.",
    example: "Sep 2026 rent / Annual insurance 2027 / Security deposit",
  },
  dueDate: {
    summary: "The date this specific occurrence is contractually or operationally due.",
    what: "The authoritative due date for this materialised due item.",
    why: "Afenda derives Upcoming, Due, and Overdue from this date instead of storing time-sensitive status that can go stale.",
    who: "The administrator using the agreement, invoice, notice, or confirmed schedule.",
    when: "Set when the due item is created and update it only when the real due date changes.",
    how: "Use the date supported by the source terms or invoice; do not use the payment date.",
    example: "01 Sep 2026",
  },
  expectedAmount: {
    summary: "The amount originally expected for this due occurrence before final invoice confirmation.",
    what: "The planning or contractual amount attached to this specific due item.",
    why: "It preserves the expected amount separately from the invoice amount so differences remain visible.",
    who: "The administrator using the agreement, schedule, or known recurring amount.",
    when: "Set when the due item is created or when the expected amount becomes known.",
    how: "Enter the expected gross amount. Do not overwrite it solely to match a later invoice.",
    example: "Expected RM15,000; invoice later received for RM15,180.",
  },
  invoiceAmount: {
    summary: "The actual amount shown on the invoice or equivalent billing evidence.",
    what: "The billed amount that becomes the payment target when it is available.",
    why: "Separating invoice from expected amount makes variances explicit and lets payment controls use the confirmed billed value.",
    who: "The administrator or finance user entering verified invoice information.",
    when: "Enter it when the invoice or equivalent billing evidence is received.",
    how: "Copy the billed gross amount from the evidence and keep the expected amount unchanged for comparison.",
    example: "Invoice total RM15,180.00",
  },
  currency: {
    summary: "The currency for this due item and all payments requested against it.",
    what: "The three-letter currency code attached to the occurrence.",
    why: "Expected, invoiced, requested, approved, and paid values must all be interpreted in an explicit currency.",
    who: "The administrator maintaining the due item.",
    when: "Usually inherited from the obligation; adjust only when this occurrence is genuinely billed in another currency.",
    how: "Use a three-letter currency code consistently.",
    example: "MYR",
  },
  invoiceNumber: {
    summary: "The supplier, landlord, insurer, or service provider's invoice reference.",
    what: "The external identifier shown on the billing document for this due item.",
    why: "It makes later matching, evidence review, and reconciliation easier without treating Corporate Administration as an accounting ledger.",
    who: "The administrator or finance user entering the invoice.",
    when: "Enter it when a billing document exists.",
    how: "Copy the invoice reference from the source document accurately.",
    example: "INV-2026-09031",
  },
  invoiceFileUrl: {
    summary: "A link to the invoice or supporting evidence for this due occurrence.",
    what: "The authorised document location used to verify the billed amount or due requirement.",
    why: "Evidence stays accessible without storing document binaries inside Corporate Administration tables.",
    who: "The administrator who can access the approved document location.",
    when: "Add it when evidence is available and keep the link current.",
    how: "Paste a stable authorised storage URL.",
    example: "Approved Google Drive or SharePoint invoice link.",
  },
  invoiceRequired: {
    summary: "Marks that this due item should have invoice evidence before payment processing is considered complete.",
    what: "An operational evidence requirement for the due item.",
    why: "It distinguishes charges that need billing evidence from obligations legitimately payable without a conventional invoice.",
    who: "The administrator or process owner maintaining the due item.",
    when: "Turn it on when the process requires an invoice or equivalent document for this occurrence.",
    how: "Enable it, then enter the invoice number and/or supporting document link when received.",
    example: "Monthly service fee invoice required; fixed statutory licence fee may not require a supplier invoice.",
  },
  disputeFlag: {
    summary: "Use this flag when the due item, amount, invoice, or entitlement is uncertain or disputed.",
    what: "An operational attention marker indicating that the record should not be treated as routine without review.",
    why: "Users can surface uncertainty without changing the payment figures or inventing a separate dispute subsystem.",
    who: "Any authorised administrator who identifies a genuine issue requiring follow-up.",
    when: "Enable it as soon as a meaningful dispute or uncertainty is known; clear it when the matter is resolved.",
    how: "Turn on the flag and record concise factual context in Notes.",
    example: "Invoice amount differs from contracted rate and is awaiting supplier clarification.",
  },
  notes: {
    summary: "Operational context for this due occurrence that does not belong in a structured field.",
    what: "Free-text clarification, exceptions, or follow-up notes attached to the due item.",
    why: "It preserves necessary context while structured values remain reportable.",
    who: "Any authorised administrator maintaining the due item.",
    when: "Use when the due item needs concise context that future reviewers should understand.",
    how: "Keep notes factual and action-oriented; use a custom field for information repeatedly needed across many records.",
    example: "Supplier confirmed corrected invoice will be issued before payment approval.",
  },
};

export const PAYMENT_GUIDANCE: Record<
  "requestAmount" | "requestNotes" | "approvedAmount" | "paidAmount" | "paymentDate" | "paymentMethod" | "paymentReference" | "paymentProofUrl",
  AfendaGuidance
> = {
  requestAmount: {
    summary: "The amount being submitted for approval against this due item's remaining balance.",
    what: "The requested settlement amount, before an approver decides how much may be paid.",
    why: "Requested and approved amounts are separate audit facts and may legitimately differ.",
    who: "The administrator initiating the payment request.",
    when: "Enter it after the due item exists and there is an amount ready to seek approval for.",
    how: "Request only the amount currently intended for approval; Afenda prevents requests that exceed the available outstanding balance.",
    example: "Invoice RM15,180 → request RM15,180.",
  },
  requestNotes: {
    summary: "Optional context the approver should know before deciding on the request.",
    what: "A concise explanation attached to the payment request.",
    why: "It keeps exceptions or rationale with the request instead of relying on separate messages.",
    who: "The administrator making the request.",
    when: "Use it when the amount, timing, evidence, or circumstances need explanation.",
    how: "State the relevant fact or requested exception briefly; avoid duplicating information already stored in structured fields.",
    example: "Urgent renewal payment required before policy expiry; evidence linked on due item.",
  },
  approvedAmount: {
    summary: "The amount the approver authorises for this payment request.",
    what: "The approved settlement ceiling for this request.",
    why: "Approval remains a distinct decision from both the requested amount and the amount ultimately paid.",
    who: "The authorised administrator acting as approver under the organisation's process.",
    when: "Set when approving a pending request.",
    how: "Enter the amount actually authorised. Afenda prevents approval above the request or the due item's remaining uncommitted balance.",
    example: "Requested RM15,180; approved RM15,000 pending clarification of RM180 variance.",
  },
  paidAmount: {
    summary: "The actual amount that was settled in this payment event.",
    what: "The amount recorded as paid after approval.",
    why: "Actual settlement may be partial and must remain distinct from both requested and approved amounts.",
    who: "The administrator recording verified payment execution.",
    when: "Enter it after the payment has actually been made or reliable settlement evidence exists.",
    how: "Record the amount actually settled; Afenda prevents it from exceeding the authorised and outstanding limits.",
    example: "Approved RM15,000; actual payment RM10,000 → partial payment remains outstanding.",
  },
  paymentDate: {
    summary: "The date the actual settlement was made.",
    what: "The business date of the recorded payment event.",
    why: "It separates settlement timing from request, approval, invoice, and due dates.",
    who: "The administrator recording the payment.",
    when: "Enter it when settlement is recorded.",
    how: "Use the actual bank/payment date supported by the payment evidence.",
    example: "12 Aug 2026",
  },
  paymentMethod: {
    summary: "The method actually used to settle this payment.",
    what: "The settlement channel such as bank transfer, direct debit, card, cheque, or another approved method.",
    why: "The actual method can differ from the obligation's normal default and is useful for later reconciliation.",
    who: "The administrator recording the payment.",
    when: "Enter it when the settlement is recorded.",
    how: "Use the standard method name used by your organisation.",
    example: "BANK_TRANSFER",
  },
  paymentReference: {
    summary: "The bank, transfer, cheque, transaction, or other settlement reference.",
    what: "The external identifier used to trace the payment event.",
    why: "It lets users match the operational payment record to bank or payment evidence during reconciliation.",
    who: "The administrator recording verified payment information.",
    when: "Enter it when the payment reference is available.",
    how: "Copy the reference from the settlement evidence accurately.",
    example: "HLB-20260812-001829",
  },
  paymentProofUrl: {
    summary: "A link to the bank slip, receipt, or other evidence showing the payment was made.",
    what: "The authorised document location for settlement evidence.",
    why: "It supports verification and reconciliation without storing payment documents directly in the database.",
    who: "The administrator recording the payment.",
    when: "Add it when payment evidence is available.",
    how: "Paste a stable authorised storage URL that permitted reviewers can open.",
    example: "Approved banking receipt or payment-proof document link.",
  },
};
