"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

import { AfendaConfirmButton } from "@/components/afenda/confirm-action";
import { AfendaEmptyState } from "@/components/afenda/page-state";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { COUNTERPARTY_IMPORT_HEADERS, MASTER_IMPORT_CLEAR_TOKEN, SITE_IMPORT_HEADERS, parseMasterImportText, type MasterImportRow, type MasterImportTarget } from "@/lib/corporate-admin/master-import";

type Change={field:string;before:string|number|boolean|null;after:string|number|boolean|null;destructive?:boolean};
type PreviewRow={rowNumber:number;code:string;action:"CREATE"|"UPDATE"|"NO_CHANGE"|"ERROR";recordId:string|null;changes:Change[];errors:string[]};
type Preview={target:MasterImportTarget;rows:PreviewRow[];previewHash:string;summary:{create:number;update:number;noChange:number;error:number;clears:number}};
type CommitResult={target:MasterImportTarget;created:number;updated:number;noChange:number;clears:number};

const SITE_EXAMPLE="SITE-KLG-HQ\tKlang Headquarters\tOFFICE\tDe Lettuce Bear Berhad\tLot 1\t\tKlang\tSelangor\t41000\tMY\tAsia/Kuala_Lumpur\t3.0449\t101.4456\tyes\tMain office";
const COUNTERPARTY_EXAMPLE="CP-CLEANPRO\tCleanPro Services Sdn Bhd\tSERVICE_PROVIDER\t202601234567\tC1234567890\tAccounts\taccounts@example.com\t+60312345678\tKlang, Selangor\tMY\thttps://example.com\tMYR\t30\tyes\tPrimary cleaning provider";
function template(target:MasterImportTarget){const headers=target==="SITE"?SITE_IMPORT_HEADERS:COUNTERPARTY_IMPORT_HEADERS;return `${headers.join("\t")}\n${target==="SITE"?SITE_EXAMPLE:COUNTERPARTY_EXAMPLE}`;}
function badge(action:PreviewRow["action"]){if(action==="ERROR")return <Badge variant="destructive">Error</Badge>;if(action==="CREATE")return <Badge>Create</Badge>;if(action==="UPDATE")return <Badge variant="secondary">Update</Badge>;return <Badge variant="outline">No change</Badge>;}

export function MasterImportAssistant({target}:{target:MasterImportTarget}){
  const router=useRouter();const [text,setText]=useState(template(target));const [rows,setRows]=useState<MasterImportRow[]>([]);const [errors,setErrors]=useState<string[]>([]);const [preview,setPreview]=useState<Preview|null>(null);const [committed,setCommitted]=useState<CommitResult|null>(null);const [busy,setBusy]=useState(false);const [fileName,setFileName]=useState<string|null>(null);
  const label=target==="SITE"?"Sites":"Counterparties";const canCommit=Boolean(preview&&preview.summary.error===0&&(preview.summary.create||preview.summary.update));
  function reset(){setPreview(null);setCommitted(null);}
  function parse(){const result=parseMasterImportText(target,text);setRows(result.rows);setErrors(result.errors);reset();if(!result.errors.length)toast.success(`${result.rows.length} ${label.toLowerCase()} parsed.`);}
  async function loadFile(file:File){const ext=file.name.split(".").pop()?.toLowerCase();if(!["csv","tsv","txt"].includes(ext??"")){toast.error("Use CSV or TSV. Native XLSX remains disabled until the approved workbook parser is installed.");return;}if(file.size>2_000_000){toast.error("Import files are limited to 2 MB.");return;}setText(await file.text());setFileName(file.name);setRows([]);setErrors([]);reset();}
  async function copyTemplate(){try{await navigator.clipboard.writeText(template(target));toast.success(`${label} import template copied.`);}catch{toast.error("Clipboard access was unavailable.");}}
  async function doPreview(){setBusy(true);try{const response=await fetch("/api/admin/corporate/operations/import/master/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target,rows})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Could not preview import");setPreview(data as Preview);setCommitted(null);}catch(error){toast.error(error instanceof Error?error.message:"Could not preview import");}finally{setBusy(false);}}
  async function commit(){if(!preview)return;setBusy(true);try{const response=await fetch("/api/admin/corporate/operations/import/master/commit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target,rows,previewHash:preview.previewHash})});const data=await response.json().catch(()=>({}));if(!response.ok){if(response.status===409)setPreview(null);throw new Error(typeof data.error==="string"?data.error:"Could not commit import");}setCommitted(data.result);toast.success(`${label} import committed.`);router.refresh();}catch(error){toast.error(error instanceof Error?error.message:"Could not commit import");}finally{setBusy(false);}}
  async function reconciliation(){if(!preview||!committed)return;const header=["row","code","decision","field","before","after","destructive"];const records=preview.rows.flatMap(row=>row.changes.length?row.changes.map(change=>[row.rowNumber,row.code,row.action,change.field,change.before??"",change.after??"",change.destructive?"YES":"NO"]):[[row.rowNumber,row.code,row.action,"","","",""]]);const tsv=[header,...records].map(r=>r.map(v=>String(v).replaceAll("\t"," ").replaceAll("\n"," ")).join("\t")).join("\n");try{await navigator.clipboard.writeText(tsv);toast.success("Reconciliation report copied.");}catch{toast.error("Clipboard access was unavailable.");}}

  return <div className="flex flex-col gap-5">
    <Card><CardHeader className="gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle>1. Paste or load {label}</CardTitle><CardDescription>Blank cells preserve current values. Use <code>{MASTER_IMPORT_CLEAR_TOKEN}</code> only on nullable fields when you explicitly intend to clear data.</CardDescription></div><Button variant="outline" onClick={()=>void copyTemplate()}>Copy {label} template</Button></CardHeader><CardContent className="flex flex-col gap-3"><div className="flex flex-col gap-2 rounded-lg border p-3"><label htmlFor={`master-import-${target}`} className="text-sm font-medium">Load CSV / TSV</label><Input id={`master-import-${target}`} type="file" accept=".csv,.tsv,.txt,text/csv,text/tab-separated-values,text/plain" onChange={event=>{const file=event.target.files?.[0];if(file)void loadFile(file);}}/><p className="text-xs text-muted-foreground">{fileName?`Loaded: ${fileName}`:"Up to 2 MB / 200 rows per transaction."}</p></div><Textarea value={text} onChange={event=>{setText(event.target.value);setFileName(null);reset();}} className="min-h-52 font-mono text-xs" spellCheck={false}/><Button className="self-start" onClick={parse}>Parse {label}</Button></CardContent></Card>
    <Card><CardHeader><CardTitle>2. Validate & preview</CardTitle><CardDescription>Afenda resolves each stable code against current Corporate master data and shows CREATE / UPDATE / NO CHANGE / ERROR before any write.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{errors.length?<Alert variant="destructive"><AlertTitle>Fix the input</AlertTitle><AlertDescription><ul className="list-disc pl-5">{errors.map(error=><li key={error}>{error}</li>)}</ul></AlertDescription></Alert>:rows.length?<div className="flex items-center gap-3"><Badge>{rows.length} parsed</Badge><Button variant="outline" disabled={busy} onClick={()=>void doPreview()}>Preview against Afenda</Button></div>:<AfendaEmptyState compact title="Not parsed yet" description={`Parse the ${label.toLowerCase()} data first.`}/>} {preview?<><div className="grid gap-3 sm:grid-cols-5">{[["Create",preview.summary.create],["Update",preview.summary.update],["No change",preview.summary.noChange],["Errors",preview.summary.error],["Clears",preview.summary.clears]].map(([name,value])=><div key={String(name)} className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">{name}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div>{preview.summary.clears?<Alert variant="destructive"><AlertTitle>Destructive clears included</AlertTitle><AlertDescription>Review every red clear before committing.</AlertDescription></Alert>:null}<div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>Row</TableHead><TableHead>Code</TableHead><TableHead>Decision</TableHead><TableHead>Changes</TableHead></TableRow></TableHeader><TableBody>{preview.rows.map(row=><TableRow key={row.rowNumber}><TableCell>{row.rowNumber}</TableCell><TableCell className="font-mono text-xs">{row.code}</TableCell><TableCell>{badge(row.action)}</TableCell><TableCell>{row.errors.length?<span className="text-sm text-destructive">{row.errors.join("; ")}</span>:row.changes.length?<ul className="flex flex-col gap-1 text-xs">{row.changes.map((change,index)=><li key={`${change.field}-${index}`} className={change.destructive?"font-medium text-destructive":undefined}>{change.field}: {String(change.before??"—")} → {change.destructive?"CLEARED":String(change.after??"—")}</li>)}</ul>:<span className="text-muted-foreground">No changes</span>}</TableCell></TableRow>)}</TableBody></Table></div></>:null}</CardContent></Card>
    <Card><CardHeader><CardTitle>3. Commit & reconcile</CardTitle><CardDescription>Commit re-derives the preview inside the transaction and rejects stale plans or any invalid row.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{committed?<Alert><AlertTitle>{label} import committed</AlertTitle><AlertDescription>{committed.created} created · {committed.updated} updated · {committed.clears} clears · {committed.noChange} unchanged.</AlertDescription></Alert>:null}<div className="flex flex-wrap gap-2">{canCommit?<AfendaConfirmButton busy={busy} title={`Commit ${label} import?`} description={`Commit ${preview!.summary.create} creates, ${preview!.summary.update} updates and ${preview!.summary.clears} explicit clears. One error or stale preview blocks the entire transaction.`} confirmLabel="Commit import" onConfirm={commit}>Commit reviewed import</AfendaConfirmButton>:<Button disabled>Commit reviewed import</Button>}{committed?<Button variant="outline" onClick={()=>void reconciliation()}>Copy reconciliation report</Button>:null}</div></CardContent></Card>
  </div>;
}
